name: Worflow Secret
on: push


jobs:
  display_value:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION  }}"
      - name: Step return value
        uses: actions/github-script@v7.0.1
        id: step-return
        with:
          script: return "Mon retour";


